---
image:
  file: Dockerfile

tasks:
  - name: Build the documentation and serve the html
    before: daps -d DC-opensuse-all html
    command: python3.9 -m http.server -d build
ports:
  - port: 8000
    onOpen: open-browser

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - mrorz.language-gettext
    - redhat.vscode-xml
    - EditorConfig.EditorConfig
    - stkb.Rewrap
    - viktorzetterstrom.non-breaking-space-highlighter
    - xshrim.txt-syntax
