= SUSE Linux Enterprise / openSUSE Leap Documentation

This is the source for the official SUSE Linux Enterprise and openSUSE Leap
documentation.

This repository hosts the documentation sources including translations (if
available) for the following products:

* SUSE Linux Enterprise Desktop (SLED)
* SUSE Linux Enterprise Server (SLES)
* SUSE Linux Enterprise Micro (SLE-Micro)
* openSUSE Leap

Released versions of the SLE documentation are published at
https://documentation.suse.com/. Released versions of the openSUSE Leap documentation can be
found at https://doc.opensuse.org/.

Beta documentation versions are available at https://susedoc.github.io/, where all commits to `main` and maintenance branches are automatically built.


== Branches

.Overview of important branches
[options="header"]
|================================================
| Name            | Purpose
| `main`          | doc development (latest development version)
| `maintenance/*` | maintenance for released versions
| `trans/*`       | translations for released versions
|================================================

*Use the main branch* as the basis of your commits/of new feature branches.


== Reporting bugs

Bugs are collected on https://bugzilla.suse.com. If possible please check for
duplicates before creating a new report. When creating a new report, use
`SUSE Linux Enterprise Desktop` or `Server` as product and in the next step the version.
As component select `Documentation`.


== Contributing

Thank you for contributing to this repo. When creating a pull request, please follow the guidelines below:

. If you want to contribute to the most recent release, create your pull request against the `main` branch. The `main` branch is protected.

. If you want to contribute to a previous release, please create your pull request against the respective `maintenance/*` branch. These branches are also protected.

. Make sure all validation (GitHub Actions) checks are passed.

. For your pull request to be reviewed, please tag the relevant subject matter expert(s) from the development team (if applicable) and members of the documentation team.

. Implement the required changes. If you have any questions, ping a documentation team member in #team-suse-docs on Slack.

. For help on style and structure, refer to the https://documentation.suse.com/style/current[Documentation Style Guide].


== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`).

*  Install the documentation environment with the following command:
+
[source]
----
sudo OneClickInstallUI https://susedoc.github.io/ymp/Documentation.ymp
----

* Basic DAPS usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** `$ daps -d DC-<YOUR_BOOK> optipng`: Always optimize new PNG images
** Learn more at https://opensuse.github.io/daps
