= SUSE Linux Enterprise / openSUSE Leap Documentation

image:https://travis-ci.org/SUSE/doc-sle.svg?branch=master["Build Status", link="https://travis-ci.org/SUSE/doc-sle"]

This is the source for the official SUSE Linux Enterprise and openSUSE Leap
documentation.

This repository hosts the documentation sources including translations (if
available) for the following products:

* SUSE Linux Enterprise Desktop (SLED)
* SUSE Linux Enterprise Server (SLES)
* openSUSE Leap

Released versions of the SLE documentation are published at
https://documentation.suse.com/. Released versions of the openSUSE Leap documentation can be
found at http://doc.opensuse.org/.

Beta documentation versions are available at https://susedoc.github.io/, where all commits to  `master` and maintenance branches are automatically built. 


== Branches

***On Sep 4, 2019, we changed to a new branching model. We have switched the default branch from `develop` to `master`.***

* *Use the master branch* as the basis of your commits/of new feature branches.

* The *develop branch has been deleted* on the server. Do not to push to the `develop` branch.
  Your changes may go lost in the medium term and never make it to the proper branch.

=== How to Update Your Local Repository

If you *created* a local clone or GitHub fork of this repo *before Sep 4, 2019, do the following*:

1. Make sure that your `master` and `develop` branches do not contain any important changes.
  If there are changes on either branch, export them using `git format-patch` or put them on a
  different branch.

1. Go to the master branch: `git checkout master`
.

1. To pull the latest changes from the remote repository and to delete references to branches
   that do not exist anymore on the server, run the following command: `git pull --prune`
.

1. Delete your local develop branch: `git branch -D develop`.

1. To check for stale local branches, run: `git branch -v`.
   For any branches marked as `[gone]`, check if you still need them. If not, delete them:
   `git branch -D BRANCHNAME`


.Overview of important branches
[options="header"]
|================================================
| Name            | Purpose
| `master`        | doc development (latest development version)
| `maintenance/*` | maintenance for released versions
| `trans/*`       | translations for released versions
|================================================

== Reporting Bugs

Bugs are collected on https://bugzilla.suse.com. If possible please check for
duplicates before creating a new report. When creating a new report, use
`SUSE Linux Enterprise Desktop` or `Server` as product and in the next step the version.
As component select `Documentation`.


== Contributing

Thank you for contributing to this repo. When creating a pull request, please follow the guidelines below:

. If you want to contribute to the most recent release, create your pull request against the `master` branch (not `develop`). The `master` branch is protected.

. If you want to contribute to a previous release, please create your pull request against the respective `maintenance/*` branch. These branches are also protected.

. Make sure all validation (Travis CI) checks are passed.

. For your pull request to be reviewed, please tag the relevant subject matter expert(s) from the development team (if applicable) and members of the documentation team.

. Implement the required changes. If you have any questions, ping a documentation team member in #susedoc on RocketChat.

. For help on style and structure, refer to the https://documentation.suse.com/style/current[Documentation Style Guide].


== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`).

*  Install the documentation environment with the following command:
+
[source]
----
sudo /sbin/OneClickInstallUI https://gitlab.nue.suse.com/susedoc/doc-ymp/raw/master/Documentation.ymp
----

* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** `$ daps -d DC-<YOUR_BOOK> optipng`: Always optimize new PNG images
** Learn more at https://opensuse.github.io/daps
