= SUSE Linux Enterprise Documentation

This is the source for the official SUSE Linux Enterprise documentation.

This repository hosts the documentation sources including translations (if
available) for the following products:

* SUSE Linux Enterprise Desktop (SLED)
* SUSE Linux Enterprise Real Time Extension (SLE RT)
* SUSE Linux Enterprise Server (SLES)

Released versions of the documentation have been published at
https://www.suse.com/documentation/.


== Branches

.Overview of important branches
[options="header"]
|================================================
| Name            | Purpose
| `devel` | SLE 12 SP1 doc development
| `maintenance/SLE12` |  SLE 12 doc maintenance
| `trans/SLE12`   | Doc translations for SLE 12
|================================================


== Contributing

If you would like to contribute, please fork this repository and send
pull requests. Always use the `develop` branch for your edits! +
Contributors with direct access to the repository are encouraged to use the
git-flow-avh workflow (package `git-flow-avh`). However, this is not a must
;-).

.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.
