= SUSE Linux Enterprise / openSUSE Leap Documentation

image:https://travis-ci.org/SUSE/doc-sle.svg?branch=develop["Build Status", link="https://travis-ci.org/SUSE/doc-sle"]

This is the source for the official SUSE Linux Enterprise and openSUSE Leap
documentation.

This repository hosts the documentation sources including translations (if
available) for the following products:

* SUSE Linux Enterprise Desktop (SLED)
* SUSE Linux Enterprise Real Time Extension (SLE RT)
* SUSE Linux Enterprise Server (SLES)
* openSUSE Leap

Released versions of the SLE documentation are published at
https://www.suse.com/documentation/, the openSUSE Leap documentation can be
found at http://doc.opensuse.org/.


== Branches

.Overview of important branches
[options="header"]
|================================================
| Name            | Purpose
| `develop`        | doc development (latest development version)
| `maintenance/*`  | maintenance for released versions
| `trans/*`        | translations for released versions
| `master`         | latest released version 
|================================================

== Reporting Bugs

Bugs are collected on https://bugzilla.suse.com. If possible please check for
duplicates before creating a new report. When creating a new report, use
`SUSE Linux Enterprise Desktop` or `Server` as product and in the next step the version.
As component select `Documentation`.


== Contributing

If you would like to contribute, please fork this repository and send
pull requests. Always use the `develop` branch for your edits! +
Contributors with direct access to the repository are encouraged to use the
git-flow-avh workflow (package `git-flow-avh`). However, this is not a must.
For help on style and structure, refer to the https://doc.opensuse.org/products/opensuse/Styleguide/opensuse_documentation_styleguide_sd/[Documentation Styleguide] 


.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is
reserved for releases only. Always commit to `develop`.

== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** Learn more at https://opensuse.github.io/daps
