== Supportability

This chapter explains how {slsa} container support plans work.

There are three guiding principles that {suse} container supportability generally adheres to:

1. The container image lifecycle follows the lifecycle of the related products.
For example {15sp1} container images will adhere to the {15sp1} lifecycle. /// New Line or in a box? ///

2. Container release status also matches the status of the related product.
For example if {15sp1} is in Alpha, Beta, RC or GA stage, the related containers also have that release status.

3. Containers are built only using the packages from the related products.
For example, {15sp1} container images will be built using the same packages as the main {15sp1} release.


=== Supported Containers on SUSE Host Environments

The following support options (Tiers) apply to *{sls}* and *{caasp}* containers on {suse} host environments.

/// Tiers below in a table for better overview? ///

==== Tier One

Containers Delivered by {suse}::

Containers delivered by {suse} are fully supported. This applies to both the container and host environment as well as all products under support, applying to both general support as well as link:https://www.suse.com/products/long-term-service-pack-support/[Long Term Service Pack Support] (LTSS).

==== Tier Two

Containers Delivered by Partners with an Agreement Ensuring a Joint Engineering Collaboration::

This Tier targets important Independent Software Vendors (ISVs).
Partner containers with a joint engineering collaboration agreement are fully supported.
This applies to both the container and host environment as well as all products under support (both general, as well as LTSS) covered by the agreement.
Products not covered by the agreement fall under Tier Three.

==== Tier Three

Any Other Third Party Containers::

The {suse} container host environment is fully supported, however issues with the third party containers themselves are to be brought up to the given container vendor.



=== Supported Container Host Environments

The following support options (Tiers) apply to:

* {sle} base containers
* Containers delivered by {suse}
* Third party container environments derived from the {slea} base containers
* Third party containers built from {slea} packages using Kiwi

/// Tiers below in a table for better overview? ///

====  Tier One

{suse} Products::

This Tier applies to *{sls}*, *{caasp}* and *{cap}*.
Both the containers and host environments delivered by {suse} are fully supported as well as all products under support, applying to both general support as well as LTSS.

====  Tier Two

Third Party Vendors with an Agreement Ensuring a Joint Engineering Collaboration::

Partner containers and host environments with a joint engineering collaboration agreement are fully supported.  This applies to both the container and host environment as well as all products under support (both general, as well as LTSS) covered by the agreement.

====  Tier Three

Selected Third Party Vendors with No Agreement::

This Tier targets for example environments delivered by *RHEL*, *OpenShift* or *Ubuntu*.
{suse}-based containers are fully supported, however issues in the host environment are to be brought up to the host environment vendor.
{suse} supports those components, which come from the SUSE base containers, as well as packages, which come from {suse} repositories.
Additional components and application in the containers are not covered by {suse} support.
A {slea} subscription is required for building a derived container.

====  Tier Four

Any Other Container Host Environment::

Any other container host environment not mentioned in the support tiers above has limited support. *Details can be negotiated with the {suse} Support Team*, which might triage the issue and recommend an alternative solutions.
In other cases issues in the host environment are to be brought up to the host environment vendor.
