
== Building Containers

This chapter documents various technologies and tools which can be used to create containers.
Most of the tools mentioned below are part of the *{sls} 15 SP2 Containers Module*.
You can see the full list of packages in the *Containers Module* in the {suse}
link:https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=15.2&arch=x86_64&query=&module=1963[Customer Center].

=== Docker

Docker is many part system for creating and managing containers, it's main part being the *Docker Open Source Engine* -
a lightweight virtualization solution to run containers simultaneously on a single control host.
Docker containers are defined in Dockerfiles, which describe how to assemble a private filesystem for a container,
and can also contain some metadata describing how to run the container.
Most Dockerfiles start from a parent image.
For an introduction on how to create custom base {sle} docker images see link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/[the Docker Open Source Engine Guide].

=== Podman

Podman is short for *Pod Manager tool* and it's purpose extends beyond just building images.
It is a *daemonless* container engine for developing, managing, and running OCI containers on your Linux System.
Podman is also the default container runtime in *openSUSE Kubic* - a certified Kubernetes distribution & container-related technologies built by the {opensuse} community.
Podman can be used to create OCI-compliant container images using a Dockerfile and a range of commands similar to Docker.
For example the `podman build` command fulfills essentially the same function as `docker build` except that it does not use the Docker daemon to do it.
Another important feature of Podman are *rootless container builds*.
By using user namespaces, which provide an isolation mechanism for Linux processes, Podman avoids requiring root privileges to create and run containers.

For instructions on how to install and use Podman see link:https://podman.io/[the Podman Documentation].


=== Buildah

Buildah facilitates building *Open Containers Initiative* (OCI) container images.
It is a complimentary tool to Podman, in fact `podman build` uses Buildah to perform container image builds.
Images can be built from already existing images, from scratch, and using Dockerfiles.
OCI images built using the *Buildah command line tool* (CLI) and the underlying OCI based technologies
(e.g. containers/image and containers/storage) are portable and can therefore run in a Docker environment.

For instructions on how to install and use Buildah see link:https://buildah.io/[the Buildah Documentation] and link:https://github.com/containers/buildah/blob/master/docs/tutorials[tutorials].

=== Open Build Service

The *Open Build Service* (OBS) provides free infrastructure for building and storing RPM packages including various container formats.
An important component of the OBS is also the *OBS Container Registry*. The link:https://registry.opensuse.org/cgi-bin/cooverview[OBS Container Registry]
provides a detailed listing of all container images built by the OBS complete with command line code to pull the images into your local docker environment.
The OBS {opensuse} link:https://build.opensuse.org/image_templates[container image templates] can be modified to specific needs and are the easiest way to create your own container branch.
Container images can either be built with *native Docker tools* - based on an existing image using a Dockerfile.
Or they can be built from scratch using the *KIWI NG imaging solution*.

TODO::
  * should this contain specific instructions on how to build containers or is linking to https://openbuildservice.org/2018/05/09/container-building-and-distribution/ enough?

=== KIWI

KIWI NG is an imaging solution that is based on an image XML description. Such a description is represented by a directory which
includes at least one `config.xml` or `.kiwi` file and may as well include other files like scripts or configuration data.

For specific information on how to install KIWI and use it to build images, see the link:http://osinside.github.io/kiwi/[KIWI documentation].
A collection of example image descriptions can be found on the link:https://github.com/OSInside/kiwi-descriptions[KIWI GitHub repository].

You can also find out more about KIWI through it's man pages by installing the `kiwi-man-pages` package and running the `man kiwi` command.


=== Building Official {slea} Images

Only images built via the Internal Build Service, *build.suse.de*, can be official.

There are no official SLE base container images on https://build.opensuse.org and the RPMs exported there are also not identical to the internal ones.
This means that it is impossible to build officially supported images on https://build.opensuse.org.
