
== Getting Containers

This chapter is about how and where to get ready built container images.

=== Comparing Containers

The link:https://github.com/GoogleContainerTools/container-diff#container-diff[container-diff]
a useful tool for analyzing and comparing container images.
*`container-diff`* can examine images along several different criteria, including:

* Docker Image History
* Image file system
* Apt packages
* RPM packages
* pip packages
* npm packages

These analyses can be performed on a single image, or a `diff` can be performed on two images to compare.
`container-diff` supports Docker images located in both a local Docker daemon and a remote registry.
Tarballs with the correct extension (.tar, .tar.gz, .tgz) can also be provided to the tool directly.

The `container-diff` package is part of the {sls} 15 SP2 *Containers Module* or it can be installed separately.
For instructions on how to install it,
see the link:https://github.com/GoogleContainerTools/container-diff#installation[container-diff documentation].


=== {sle} Base images

=== {suse} Container Properties

=== {suse} Registry

=== On-prem Registry

=== 3rd Party Container
