
== Getting Containers

This chapter is about how and where to get ready built container images.

=== Comparing Containers

The link:https://github.com/GoogleContainerTools/container-diff#container-diff[container-diff]
a useful tool for analyzing and comparing container images.
*`container-diff`* can examine images along several different criteria, including:

* Docker Image History
* Image file system
* Apt packages
* RPM packages
* pip packages
* npm packages

These analyses can be performed on a single image, or a `diff` can be performed on two images to compare.
`container-diff` supports Docker images located in both a local Docker daemon and a remote registry.
Tarballs with the correct extension (.tar, .tar.gz, .tgz) can also be provided to the tool directly.

The `container-diff` package is part of the {sls} 15 SP2 *Containers Module* or it can be installed separately.
For instructions on how to install it,
see the link:https://github.com/GoogleContainerTools/container-diff#installation[container-diff documentation].


=== {sle} Base images

=== {suse} Container Properties

=== {suse} Registry

`registry.suse.com` is a kind of storage, from whoch you can pull official tested and updated SLE and SLES base container images.
It's free for everyone to use, but much more useful without an active customer subscription on the container host.
That is because the subscription is used by the container and it is needed for the container images to get updates.
https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#Customizing-Pre-build-Images
Has no UI, no list of images. UI is in plan. there is no authentication yet, so the lack of a list of images is a "feature".
The SCC team is responsible for maintaining the registry and for the web UI.
TODO::
  * figure out who to ask in SCC
All available images and how the image names are derived is mentioned in the examples in the docker quickstart.
https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#id-1.14.5.7.7



=== On-prem Registry

=== 3rd Party Container
