== Building Containers

=== Docker

Docker Open Source Engine is a lightweight virtualization solution to run multiple virtual units (containers) simultaneously on a single control host.
For an introduction on how to create custom {sle} docker images see link:https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/[the Docker Open Source Engine Guide].

=== Podman

Podman is short for *Pod Manager tool*. It is daemonless container engine for developing, managing, and running OCI containers on your Linux System.
Podman is the default container runtime in openSUSE Kubic - Certified Kubernetes distribution & container-related technologies built by the {opensuse} community.
For instructions on how to install and use Podman see link:https://podman.io/[the Podman Dcumentation].
NOTE:: Limitations/differences compared to other tools? More detailed info on how to use it?

=== Buildah

Buildah is a tool developed by {suse} that facilitates building Open Containers Initiative (OCI) container images.
Images can be built from already existing images, from scratch, and using Dockerfiles.
OCI images built using the Buildah command line tool (CLI) and the underlying OCI based technologies
(e.g. containers/image and containers/storage) are portable and can therefore run in a Docker environment.
For instructions on how to install and use Buildah see link:https://buildah.io/[the Buildah Documentation] and link:https://github.com/containers/buildah/blob/master/docs/tutorials[tutorials].

=== OBS

The Open Build Service (OBS) provides free infrastructure for building and storing RPM packages including various container formats.
The link:https://registry.opensuse.org/cgi-bin/cooverview[OBS Container Registry]
provides a detailed listing of all container images built by the OBS complete with command line code to pull the images into your local docker environment.
The OBS {opensuse} link:https://build.opensuse.org/image_templates[container image templates] can be modified to specific needs and are the easiest way to create your own container branch.
Container images can either be built with native Docker tools - based on an existing image using a Dockerfile.
Or they can be built from scratch using the KIWI imaging solution.
NOTE:: this should contain specific instructions on how to build containers or is linking to https://openbuildservice.org/2018/05/09/container-building-and-distribution/ enough?

=== KIWI

KIWI NG is an imaging solution that is based on an image XML description. Such a description is represented by a directory which
includes at least one config.xml or .kiwi file and may as well include other files like scripts or configuration data.

For specific information on how to install KIWI and use it to build images, see the link:http://osinside.github.io/kiwi/[KIWI documentation].
A collection of example image descriptions can be found on the link:https://github.com/OSInside/kiwi-descriptions[KIWI GitHub repository].

You can also find out more about KIWI through it's man pages by installing the `kiwi-man-pages` package and running the `man kiwi` command.
