=== Documentation Conventions

The following notices and typographical conventions are used in this documentation:

* [path]``/etc/passwd`` : directory names and file names
* `<PLACEHOLDER>`: replace `<PLACEHOLDER>` with the actual value
* [var]``PATH``: the environment variable PATH
* `ls`, [option]``--help``: commands, options, and parameters
* [username]``user`` : users or groups
* [package]#package name# : name of a package
* kbd:[Alt], kbd:[Alt+F1] : a key to press or a key combination; keys are shown in uppercase as on a keyboard
* menu:File[Save As] : menu items, buttons
* _Dancing Penguins_ (Chapter __Penguins__, ↑Another Manual): This is a reference to a chapter in another manual.
* Commands that must be run with {rootuser} privileges. Often you can also prefix these commands with the `sudo` command to run them as non-privileged user.
+
[source,bash,subs="attributes"]
----
sudo command
----
* Commands that can be run by non-privileged users.
+
[source,bash,subs="attributes"]
----
command
----
* Notices:
+
[WARNING]
====
Vital information you must be aware of before proceeding.
Warns you about security issues, potential loss of data, damage to hardware, or physical hazards.
====
+
[IMPORTANT]
====
Important information you should be aware of before proceeding.
====
+
[NOTE]
====
Additional information, for example about differences in software versions.
====
+
[TIP]
====
Helpful information, like a guideline or a piece of practical advice.
====
+
