=== Feedback

Several feedback channels are available:

Bugs and Enhancement Requests::
For services and support options available for your product, refer to http://www.suse.com/support/.
+
To report bugs for a product component, go to https://scc.suse.com/support/requests, log in, and click menu:Create New[].

User Comments::
We want to hear your comments about and suggestions for this manual and the other documentation included with this product.
Use the User Comments feature at the bottom of each page in the online documentation or go to https://documentation.suse.com/, click Feedback at the bottom of the page and enter your comments in the Feedback Form.

Mail::
For feedback on the documentation of this product, you can also send a mail to ``doc-team@suse.com``.
Make sure to include the document title, the product version and the publication date of the documentation.
To report errors or suggest enhancements, provide a concise description of the problem and refer to the respective section number and page (or URL).
