#!/bin/bash

# Translations selector. Returns list of languages that matches selected criterion.
#
# Copyright (C) 2018, SUSE Linux
# Authors: Alessio Adamo
#
# All rights reserved.
#
# The script is in public domain. Do anything you want with it.
#

while [[ $# -gt 0 ]] && [[ ."$1" = .--* ]] ;
do
    opt="$1";
    shift;
    case "$opt" in
        "--" ) break 2;;
        "--dc-name" )
           DC_NAME="$1"; shift;;
        "--dc-name="* )
           DC_NAME="${opt#*=}";;
        "--pdf-name" )
           PDF_NAME=true;;
        "--html-name" )
           HTML_NAME=true;;
        "--text-name" )
           TEXT_NAME=true;;
        *) echo >&2 "Invalid option: $@"; exit 1;;
   esac
done

MAIN_NAME=${DC_NAME:3}
ROOTID=$(cat $DC_NAME | grep ROOTID= | cut -f2 -d'"')
if [ " $ROOTID" = " " ]; then ROOTID=$MAIN_NAME; fi

if [ "$PDF_NAME" = true ]; then 
    echo "build/${MAIN_NAME}/${ROOTID}_color_en.pdf"
elif [ "$HTML_NAME" = true ]; then 
    echo "build/${MAIN_NAME}/single-html/${ROOTID}/index.html"
elif [ "$TEXT_NAME" = true ]; then 
    echo "build/${MAIN_NAME}/${ROOTID}.txt"
else
    echo >&2 "No output format specified"
    exit 1
fi
