#!/bin/bash

# Translations selector. Returns list of languages that matches selected criterion.
#
# Copyright (C) 2018, SUSE Linux
# Authors: Alessio Adamo
#
# All rights reserved.
#
# The script is in public domain. Do anything you want with it.
#

cd `dirname $0`

if [ -z "$1" ]; then
    echo >&2 "No argument supplied"
    exit 1
fi

for arg in "$@"
do
    if [ ! -f ../$arg ]; then
        echo >&2 "File '$arg' not found!"
        exit 2
    fi
done

echo "Finding XML sources of selected books..."
for DC_FILE in $*; do
    echo -ne "\nXML sources of $DC_FILE: "
    for SOURCE_FILE in $(daps -d ../$DC_FILE list-srcfiles); do
        echo $SOURCE_FILE | grep -q '/xml/'
        if [ ${PIPESTATUS[1]} -eq "0" ]; then
            echo -n "xml/$(basename $SOURCE_FILE) "
        fi
    done
echo; echo
done
