---
name: CI

on:
  push
  #  branches: [main]

jobs:
  dc-files: # Job that list DC files
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.set-dc-files.outputs.file }} # generate output name file by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dc-files # Give it an id to handle to get step outputs in the outputs key above
        run: |
          shopt -s extglob
          echo "::set-output name=file::$(ls DC!(*-all|*-html) | jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named file base on ls command transformed to JSON thanks to jq

  validate:
    runs-on: ubuntu-latest
    needs: [dc-files] # Depends on previous job
    strategy:
      matrix:
        dc-file: ${{fromJson(needs.dc-files.outputs.file)}} # List matrix strategy from directories dynamically

    steps:
      - uses: actions/checkout@v2
        with:
          repository: openSUSE/daps
          path: daps

      - name: Listing content of $GITHUB_WORKSPACE
        id: workspace
        run: |
          ls $GITHUB_WORKSPACE

      - name: Installing packages
        id: install
        run: |
          sudo apt-get install libxml2-utils

      - name: ${{matrix.dc-file}}
        id: echo
        run: |
          echo ${{matrix.dc-file}}

    
