---
name: CI

on:
  push
  #  branches: [main]

jobs:
  dc-files: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dc-files # Give it an id to handle to get step outputs in the outputs key above
        run: |
          shopt -s extglob
          echo "::set-output name=dir::$(ls DC!(*-all|*-html) | jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq
  validate:
    runs-on: ubuntu-latest
    needs: [dc-files] # Depends on previous job
    strategy:
      matrix:
        dc-file: ${{fromJson(needs.dc-files.outputs.dir)}} # List matrix strategy from directories dynamically
    steps:
      - run: echo ${{matrix.dc-file}}
    
