---
name: daps CI

on:
  push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Output env variables
        run: |
          # Just for debugging purposes. Can be removed once it's stable
          echo "PWD=$PWD"
          echo "Default branch=${default-branch}"
          echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION=$GITHUB_ACTION"
          echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"

      - uses: actions/checkout@v2

      - name: Pull Docker container
        run: sudo docker pull susedoc/ci

      - name: Validate
        run: |
          docker run -v $PWD:/home/ \
            --env TERM=$TERM \
            --workdir /home susedoc/ci \
            daps -vv -d DC-SLES-deployment validate
